<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <?php echo $this->headTitle() . PHP_EOL; ?>
    <?php echo $this->headMeta()->prependName('keywords', 'Portfolio') . PHP_EOL; ?>
    <?php echo $this->headLink(array('rel' => 'icon', 'href' => '/favicon.ico')); ?>
    <link rel="stylesheet" href="/css/app.css">
    
</head>
<body>


    <!-- Menu -->
    <?php 
        $config    = new Zend_Config_Xml(APPLICATION_PATH . "/configs/navigation.xml", "nav");
        $container = new Zend_Navigation($config);
        $nav       = $this->navigation($container);
    ?>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <?php echo $nav->menu()->setPartial('partials/menu-bootstrap.phtml'); ?>
    </nav>
    

    <!-- Content -->
    <div class="container">

        <!-- Breadcrumbs -->
        <?php echo $nav->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setPartial('partials/breadcrumb-bootstrap.phtml'); ?>

        <?= $this->layout()->content; ?>
    </div>
    

    <!-- Footer -->
    <footer class="main-footer">
        <nav>
            <a href="sitemap">Plan du site</a>
        </nav>
    </footer>

    <!-- JavaScript -->
    <script type="text/javascript" src="/js/app.js"></script>
</body>
</html>